// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FlowerPot
{
    internal sealed partial class Vsix
    {
        public const string Id = "FlowerPot.0ba82257-9f3e-4fb4-ba61-73ddffaece95";
        public const string Name = "FlowerPot";
        public const string Description = @"Inserts a flower pot above a C# file.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
